# fly.toml app configuration file generated for iago-cavalcante on 2024-10-31T11:11:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iagocavalcante'
primary_region = 'gru'
kill_signal = 'SIGTERM'

[build]

[deploy]
release_command = '/app/bin/migrate'

[env]
PHX_HOST = 'iagocavalcante.com'
PORT = '8080'

[mounts]
source = "iagocavalcante"
destination = "/data/posts"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
