# fly.toml file generated for iagocavalcante on 2023-02-23T22:58:12-03:00

app = "iagocavalcante"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
release_command = "/app/bin/migrate"

[env]
PHX_HOST = "iagocavalcante.com"
PORT = "8080"

[mounts]
source = "app"
destination = "/data/posts"

[experimental]
auto_rollback = true

[http_service]
internal_port = 8080
force_https = false
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000
