apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-posts-pvc
  namespace: iagocavalcante-blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path