name: Deploy Site to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Elixir
    #   uses: actions/setup-elixir@v1
    #   with:
    #     elixir-version: 1.14

    # - name: Install dependencies
    #   run: mix deps.get

    # - name: Check code quality with Credo
    #   run: mix credo

    # - name: Run tests
    #   run: mix test

    # - name: Build the Phoenix app
    #   run: mix compile

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}
